import type { Express,Request,Response } from "express";
import { z } from "zod";
import { isAuthenticated,isLocallyAuthenticatable } from "../auth.js";
import { storage } from "../storage.js";
import { safeErrorMessage } from "../safeErrors.js";
import { productionTradeTrustApplicationService as service } from "./applicationService.js";
import { containsDemoIdentifier } from "../demo-runtime/productionBoundaryGuard.js";
const text=z.string().trim().min(1).max(255),assertions=z.object({assertions:z.array(z.object({assertionCode:text,value:z.string().trim().min(1).max(2000)}).strict()).min(1).max(100)}).strict();
const registration=z.object({legalName:text,tradingNames:z.array(text).max(20).default([]),organizationType:text,jurisdiction:text,registrationIdentifiers:z.array(z.object({scheme:text,value:text}).strict()).min(1).max(20),declaredActivities:z.array(z.object({code:text,description:text.optional()}).strict()).min(1).max(50)}).strict();
async function actor(req:Request,res:Response){const id=req.user?.claims.sub;if(!id){res.status(401).json({message:"Unauthorized"});return null;}const user=await storage.getAuthenticationUser(id);if(!isLocallyAuthenticatable(user)||user.role!=="trader"){res.status(403).json({message:"Local trader account required."});return null;}return user.id;}
function respond(res:Response,value:Record<string,unknown>,created=false){const status=value.status;if(status==="forbidden"||status==="actor_invalid")res.status(403).json({message:"Operation not authorized."});else if(status==="not_found")res.status(404).json({message:"Authoritative resource not found."});else if(status==="conflict"||status==="owner_exists")res.status(409).json({message:"Authority state conflicts with this request."});else res.status(created?201:200).json(value);}
function rejectDemoIdentifiers(res:Response,values:readonly unknown[]){if(!containsDemoIdentifier(values))return false;res.status(400).json({message:"Demo identifiers are not accepted by production authority endpoints.",code:"demo_identifier_not_allowed"});return true;}
export function registerTradeTrustApplicationRoutes(app:Express){
  app.get("/api/organizations/current",isAuthenticated,async(req,res)=>{try{const user=await actor(req,res);if(!user)return;res.json(await service.getCurrentOrganization(user));}catch{res.status(503).json({state:"unavailable",organization:null});}});
  app.post("/api/organizations",isAuthenticated,async(req,res)=>{try{const user=await actor(req,res);if(!user)return;const parsed=registration.safeParse(req.body);if(!parsed.success)return void res.status(400).json({message:"Invalid organization registration."});respond(res,await service.createOrganization(user,parsed.data),true);}catch{res.status(503).json({message:"Organization registration temporarily unavailable."});}});
  app.post("/api/organizations/:organizationId/memberships",isAuthenticated,async(req,res)=>{try{if(rejectDemoIdentifiers(res,[req.params.organizationId,req.body?.userId]))return;const user=await actor(req,res);if(!user)return;const parsed=z.object({userId:text,role:z.enum(["owner","member"])}).strict().safeParse(req.body);if(!parsed.success)return void res.status(400).json({message:"Invalid membership."});respond(res,await service.addMembership(user,{organizationId:req.params.organizationId,...parsed.data}),true);}catch{res.status(503).json({message:"Membership operation temporarily unavailable."});}});
  app.patch("/api/organizations/:organizationId/memberships/:membershipId",isAuthenticated,async(req,res)=>{try{if(rejectDemoIdentifiers(res,[req.params.organizationId,req.params.membershipId]))return;const user=await actor(req,res);if(!user)return;const parsed=z.object({role:z.enum(["owner","member"]),status:z.enum(["active","inactive"])}).strict().safeParse(req.body);if(!parsed.success)return void res.status(400).json({message:"Invalid membership change."});respond(res,await service.changeMembership(user,{organizationId:req.params.organizationId,membershipId:req.params.membershipId,...parsed.data}));}catch{res.status(503).json({message:"Membership operation temporarily unavailable."});}});
  app.post("/api/organizations/:organizationId/profile-revisions/:profileRevisionId/evidence",isAuthenticated,async(req,res)=>{try{if(rejectDemoIdentifiers(res,[req.params.organizationId,req.params.profileRevisionId]))return;const user=await actor(req,res);if(!user)return;const parsed=assertions.safeParse(req.body);if(!parsed.success)return void res.status(400).json({message:"Invalid evidence."});respond(res,await service.submitOrganizationEvidence(user,req.params.organizationId,req.params.profileRevisionId,parsed.data),true);}catch{res.status(503).json({message:"Evidence submission temporarily unavailable."});}});
  app.post("/api/organizations/:organizationId/profile-revisions/:profileRevisionId/verification",isAuthenticated,async(req,res)=>{try{if(rejectDemoIdentifiers(res,[req.params.organizationId,req.params.profileRevisionId]))return;const user=await actor(req,res);if(!user)return;respond(res,await service.initiateOrganizationVerification(user,req.params.organizationId,req.params.profileRevisionId));}catch(error){console.error(`Organization verification failed safely: ${safeErrorMessage(error)}`);res.status(503).json({message:"Organization verification temporarily unavailable."});}});
  app.post("/api/drafts/:offerId/evidence",isAuthenticated,async(req,res)=>{try{if(rejectDemoIdentifiers(res,[req.params.offerId]))return;const user=await actor(req,res);if(!user)return;const parsed=assertions.safeParse(req.body);if(!parsed.success)return void res.status(400).json({message:"Invalid evidence."});respond(res,await service.submitOfferEvidence(user,req.params.offerId,parsed.data),true);}catch{res.status(503).json({message:"Evidence submission temporarily unavailable."});}});
  app.post("/api/organizations/:organizationId/trade-participation",isAuthenticated,async(req,res)=>{try{if(rejectDemoIdentifiers(res,[req.params.organizationId,req.body?.profileRevisionId,req.body?.commodity?.commodityId]))return;const user=await actor(req,res);if(!user)return;const parsed=z.object({profileRevisionId:text,activityCode:text,commodity:z.object({commodityId:text,commodityClassification:text.nullable(),jurisdiction:text.nullable()}).strict().nullable()}).strict().safeParse(req.body);if(!parsed.success)return void res.status(400).json({message:"Invalid activity context."});const value=await service.evaluateTradeParticipation({organizationId:req.params.organizationId,userId:user,...parsed.data});if(!value)return void res.status(409).json({message:"Authoritative evidence unavailable."});res.json(value);}catch{res.status(503).json({message:"Participation evaluation temporarily unavailable."});}});
}
