import React from "react";
import { Link,useLocation } from "wouter";
import { LayoutDashboard,ShieldCheck,Globe,Package,ShoppingCart,FileText,Settings,Building2,BellRing } from "lucide-react";
import { cn } from "@/lib/utils";
import { useAuth } from "@/hooks/useAuth";
import { useOrganizationContext } from "@/hooks/useOrganizationContext";
interface Props{isOpen:boolean;onClose():void}
const items=[[LayoutDashboard,"Dashboard","/dashboard"],[BellRing,"Action Center","/action-center"],[Building2,"Organization","/organization"],[ShieldCheck,"Organization verification","/verification"],[Globe,"Marketplace","/marketplace"],[Package,"Seller offers","/my-offers"],[ShoppingCart,"Orders","/orders"],[FileText,"Contracts","/contracts"],[Settings,"Settings","/settings"]] as const;
export function AppSidebar({isOpen,onClose}:Props){const[location]=useLocation(),auth=useAuth(),organization=useOrganizationContext(auth.isAuthenticated);const current=organization.context?.state==="available"?organization.context.organization:null;return <>{isOpen&&<div className="fixed inset-0 z-30 bg-black/20 backdrop-blur-sm lg:hidden" onClick={onClose}/>}<aside className={cn("fixed left-0 top-16 z-40 h-[calc(100vh-4rem)] w-64 border-r bg-white transition-transform lg:translate-x-0",isOpen?"translate-x-0":"-translate-x-full")}><div className="flex h-full flex-col"><nav className="flex-1 space-y-1 overflow-y-auto px-3 py-4">{items.map(([Icon,label,href])=><Link key={href} href={href} onClick={onClose} className={cn("flex items-center rounded-lg px-3 py-2 text-sm font-medium",location.startsWith(href)?"bg-emerald-100 text-emerald-900":"text-neutral-700 hover:bg-neutral-100")}><Icon className="mr-3 h-5 w-5"/>{label}</Link>)}</nav><div className="border-t p-4 text-xs text-neutral-600"><p className="font-semibold text-neutral-900">Server-authoritative status</p>{current?<><p className="mt-1">{current.displayName}</p><p>Verification: {current.verification.phase.replaceAll("_"," ")}</p><p>Trust: {current.verification.canonicalTrustStatus??"not established"}</p></>:<p className="mt-1">Organization setup required</p>}</div></div></aside></>}
