interface QueryPool { query<Row=Record<string,unknown>>(sql:string,values?:readonly unknown[]):Promise<{rows:Row[]}> }

export function createAdminControlPlaneReadModel(pool:QueryPool){return Object.freeze({
  async overview(){const r=await pool.query<{principals:number;owners:number;assignments:number;audit_events:number}>(`SELECT (SELECT count(id)::int FROM platform_principals WHERE status='active') principals,(SELECT count(id)::int FROM platform_ownership_assignments WHERE status='active') owners,(SELECT count(id)::int FROM platform_role_assignments WHERE status='active') assignments,(SELECT count(id)::int FROM security_audit_events) audit_events`);return Object.freeze({...r.rows[0],health:"operational",modules:Object.freeze([{id:"overview",maturity:"ACTIVE_BASELINE"},{id:"platform_administration",maturity:"ACTIVE_BASELINE"},{id:"security_audit",maturity:"ACTIVE_BASELINE"},{id:"organizations_users",maturity:"ACTIVE_BASELINE"},{id:"verification",maturity:"DEFINED"},{id:"risk",maturity:"DEFINED"},{id:"enforcement",maturity:"DEFINED"},{id:"trade_operations",maturity:"DEFINED"},{id:"documents",maturity:"DEFINED"},{id:"shipping_fulfilment",maturity:"DEFINED"},{id:"settlement_finance",maturity:"DEFINED"},{id:"claims_disputes",maturity:"DEFINED"},{id:"support",maturity:"DEFINED"}])})},
  async owners(){const r=await pool.query(`SELECT o.id AS "assignmentId",o.principal_id AS "principalId",p.user_id AS "userId",o.status,o.authority_source AS "authoritySource",o.granted_at AS "grantedAt",o.version FROM platform_ownership_assignments o JOIN platform_principals p ON p.id=o.principal_id ORDER BY o.granted_at,o.id`);return Object.freeze(r.rows.map(row=>Object.freeze({...row})))},
  async principals(){const r=await pool.query(`SELECT id AS "principalId",user_id AS "userId",status,created_at AS "createdAt" FROM platform_principals ORDER BY created_at,id`);return Object.freeze(r.rows.map(row=>Object.freeze({...row})))},
  async roleAssignments(){const r=await pool.query(`SELECT id AS "assignmentId",principal_id AS "principalId",role,status,granted_at AS "grantedAt",revoked_at AS "revokedAt" FROM platform_role_assignments ORDER BY granted_at,id`);return Object.freeze(r.rows.map(row=>Object.freeze({...row})))},
  async users(){const r=await pool.query(`SELECT u.id AS "userId",u.email,CASE WHEN u.login_enabled IS TRUE AND u.credential_status='active' THEN 'active' ELSE 'restricted' END AS "accountStatus",(u.email_verified_at IS NOT NULL) AS "emailVerified",EXISTS(SELECT 1 FROM platform_principals p WHERE p.user_id=u.id AND p.status='active') AS "platformPrincipal",u.company_name AS "declaredCompanyName" FROM public.users u ORDER BY u.created_at,u.id LIMIT 100`);return Object.freeze(r.rows.map(row=>Object.freeze({...row})))},
})}
