import { replayVerificationHistory } from "../trade-trust-application/verificationReadModelAdapter.js";
interface QueryPool { query<Row=Record<string,unknown>>(sql:string,values?:readonly unknown[]):Promise<{rows:Row[];rowCount?:number}> }

export function createAdminControlPlaneReadModel(pool:QueryPool){return Object.freeze({
  async overview(){const r=await pool.query<{principals:number;owners:number;assignments:number;audit_events:number}>(`SELECT (SELECT count(id)::int FROM platform_principals WHERE status='active') principals,(SELECT count(id)::int FROM platform_ownership_assignments WHERE status='active') owners,(SELECT count(id)::int FROM platform_role_assignments WHERE status='active') assignments,(SELECT count(id)::int FROM security_audit_events) audit_events`);return Object.freeze({...r.rows[0],health:"operational",modules:Object.freeze([{id:"overview",maturity:"ACTIVE_BASELINE"},{id:"platform_administration",maturity:"ACTIVE_BASELINE"},{id:"security_audit",maturity:"ACTIVE_BASELINE"},{id:"organizations_users",maturity:"ACTIVE_BASELINE"},{id:"verification",maturity:"ACTIVE_BASELINE"},{id:"risk",maturity:"ACTIVE_BASELINE"},{id:"enforcement",maturity:"ACTIVE_BASELINE"},{id:"trade_operations",maturity:"ACTIVE_BASELINE"},{id:"documents",maturity:"DEFINED"},{id:"shipping_fulfilment",maturity:"DEFINED"},{id:"settlement_finance",maturity:"DEFINED"},{id:"claims_disputes",maturity:"DEFINED"},{id:"support",maturity:"DEFINED"}])})},
  async owners(){const r=await pool.query(`SELECT o.id AS "assignmentId",o.principal_id AS "principalId",p.user_id AS "userId",o.status,o.authority_source AS "authoritySource",o.granted_at AS "grantedAt",o.version FROM platform_ownership_assignments o JOIN platform_principals p ON p.id=o.principal_id ORDER BY o.granted_at,o.id`);return Object.freeze(r.rows.map(row=>Object.freeze({...row})))},
  async principals(){const r=await pool.query(`SELECT id AS "principalId",user_id AS "userId",status,created_at AS "createdAt" FROM platform_principals ORDER BY created_at,id`);return Object.freeze(r.rows.map(row=>Object.freeze({...row})))},
  async roleAssignments(){const r=await pool.query(`SELECT id AS "assignmentId",principal_id AS "principalId",role,status,granted_at AS "grantedAt",revoked_at AS "revokedAt" FROM platform_role_assignments ORDER BY granted_at,id`);return Object.freeze(r.rows.map(row=>Object.freeze({...row})))},
  async users(){const r=await pool.query(`SELECT u.id AS "userId",u.email,CASE WHEN u.login_enabled IS TRUE AND u.credential_status='active' THEN 'active' ELSE 'restricted' END AS "accountStatus",(u.email_verified_at IS NOT NULL) AS "emailVerified",EXISTS(SELECT 1 FROM platform_principals p WHERE p.user_id=u.id AND p.status='active') AS "platformPrincipal",u.company_name AS "declaredCompanyName" FROM public.users u ORDER BY u.created_at,u.id LIMIT 100`);return Object.freeze(r.rows.map(row=>Object.freeze({...row})))},
  async organizations(){const r=await pool.query<{organizationId:string;profileRevisionId:string;legalName:string;lifecycle:string;memberCount:number;activeMemberCount:number;reviewOutcome:string|null;reviewPolicyVersion:string|null}>(`SELECT DISTINCT ON (profile.organization_id)
    profile.organization_id AS "organizationId",profile.organization_profile_revision_id AS "profileRevisionId",
    profile.contract_payload->'legal_identity_projection'->>'legal_name' AS "legalName",
    profile.contract_payload->>'organization_lifecycle' AS lifecycle,
    (SELECT count(*)::int FROM public.organization_memberships membership WHERE membership.organization_id=profile.organization_id) AS "memberCount",
    (SELECT count(*)::int FROM public.organization_memberships membership WHERE membership.organization_id=profile.organization_id AND membership.status='active') AS "activeMemberCount",
    review.outcome AS "reviewOutcome",review.policy_version AS "reviewPolicyVersion"
    FROM public.organization_registry_profile_revisions profile
    LEFT JOIN LATERAL(SELECT outcome,policy_version FROM public.vre_verification_reviews WHERE organization_id=profile.organization_id ORDER BY created_at DESC,id DESC LIMIT 1)review ON true
    ORDER BY profile.organization_id,profile.created_at DESC,profile.organization_profile_revision_id DESC LIMIT 100`);
    const rows=[];for(const row of r.rows){const history=await replayVerificationHistory(pool,row.organizationId);const latest=history[0];rows.push(Object.freeze({...row,verificationDecision:latest?.decision??null,trustStatus:latest?.trust??null,verificationPolicyVersion:latest?.policyVersion??row.reviewPolicyVersion??null}));}return Object.freeze(rows)},
  async tradeOperations(){const [offers,orders,contracts]=await Promise.all([
    pool.query(`SELECT offer.id,offer.status::text AS status,offer.type::text AS type,commodity.name AS commodity,offer.quantity::text AS quantity,offer.unit,offer.price_per_unit::text AS "pricePerUnit",offer.currency,offer.seller_org_id AS "sellerOrganizationId",offer.created_at AS "createdAt" FROM public.offers offer JOIN public.commodities commodity ON commodity.id=offer.commodity_id ORDER BY offer.created_at DESC,offer.id DESC LIMIT 100`),
    pool.query(`SELECT id,offer_id AS "offerId",buyer_organization_id AS "buyerOrganizationId",seller_organization_id AS "sellerOrganizationId",status,quantity::text,unit,total_amount::text AS "totalAmount",currency,order_version AS "orderVersion",created_at AS "createdAt" FROM public.orders WHERE order_fingerprint IS NOT NULL ORDER BY created_at DESC,id DESC LIMIT 100`),
    pool.query(`SELECT id,order_id AS "orderId",offer_id AS "offerId",buyer_organization_id AS "buyerOrganizationId",seller_organization_id AS "sellerOrganizationId",status,total_amount::text AS "totalAmount",currency,contract_version AS "contractVersion",created_at AS "createdAt" FROM public.contracts WHERE contract_fingerprint IS NOT NULL ORDER BY created_at DESC,id DESC LIMIT 100`)]);return Object.freeze({offers:Object.freeze(offers.rows),orders:Object.freeze(orders.rows),contracts:Object.freeze(contracts.rows)})},
})}
