import { useQuery } from "@tanstack/react-query";
import { Link } from "wouter";
import { BellRing, FileSignature, UserPlus, Globe2, ClipboardCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

type ActionItem={kind:string;id:string;organizationId:string;title:string;detail?:string;contractReference?:string;counterparty?:string;commodity?:string;value?:string;currency?:string;delivery?:string;preparedBy?:string;readiness?:string;approvalStatus?:string;mandateEligibility?:string;action?:string};
type Center={generatedAt:string;authorityNotice:string;items:ActionItem[]};
const icon=(kind:string)=>kind==="CONTRACT_SIGNATURE"?FileSignature:kind==="INVITATION_ACCEPTANCE"?UserPlus:kind==="DOMAIN_VERIFICATION"?Globe2:ClipboardCheck;
export default function ActionCenter(){const query=useQuery<Center>({queryKey:["/api/action-center"]});if(query.isLoading)return <p className="p-6 text-sm text-neutral-600">Loading your action center…</p>;return <div className="space-y-6" data-testid="action-center"><div><div className="flex items-center gap-3"><BellRing className="h-8 w-8 text-emerald-700"/><div><h1 className="text-2xl font-semibold">Action Center</h1><p className="text-neutral-600">Focused work that needs your attention.</p></div></div><p className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">{query.data?.authorityNotice??"Tasks never grant authority."}</p></div>{query.data?.items.length? <div className="grid gap-4 lg:grid-cols-2">{query.data.items.map(item=>{const Icon=icon(item.kind);return <Card key={`${item.kind}-${item.id}`}><CardHeader><div className="flex items-start gap-3"><span className="rounded-lg bg-emerald-100 p-2"><Icon className="h-5 w-5 text-emerald-800"/></span><div><CardTitle className="text-base">{item.title}</CardTitle><CardDescription>{item.detail??item.contractReference}</CardDescription></div></div></CardHeader><CardContent className="space-y-2 text-sm">{item.counterparty&&<><p><b>Counterparty:</b> {item.counterparty}</p><p><b>Commodity:</b> {item.commodity}</p><p><b>Value:</b> {item.value} {item.currency}</p><p><b>Delivery:</b> {item.delivery}</p><p><b>Prepared by:</b> {item.preparedBy}</p><p><b>Readiness:</b> {item.readiness} · {item.approvalStatus}</p><p><b>Your mandate:</b> {item.mandateEligibility}</p></>}{item.action&&<Button asChild className="mt-2"><Link href={item.action}>Review contract</Link></Button>}{item.kind==="MEMBERSHIP_APPROVAL"&&<Button asChild variant="outline"><Link href="/organization">Review team request</Link></Button>}{item.kind==="DOMAIN_VERIFICATION"&&<Button asChild variant="outline"><Link href="/organization">Review domain</Link></Button>}</CardContent></Card>})}</div>:<Card><CardHeader><CardTitle>You’re all caught up</CardTitle><CardDescription>No pending organization or contract actions are assigned to you.</CardDescription></CardHeader></Card>}</div>}
