import React from "react";
import { Link, useLocation, useRoute } from "wouter";
import { ArrowRight, Building2, CheckCircle2, FileCheck2, MapPin, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { demoApi, DemoApiError } from "@/features/demo/api";
import { ASSURANCE_COPY, formatUnit } from "@/features/demo/presentation";
import { demoRoutes } from "@/features/demo/routes";
import { GuidedProgress } from "@/features/demo/GuidedProgress";
import type { DemoEvidence, DemoMissionView, DemoOffer, DemoOrganization } from "@/features/demo/types";

export default function DemoOfferPage() {
  const [,params] = useRoute("/demo/offers/:offerId"); const [,navigate]=useLocation(); const missionId=new URLSearchParams(window.location.search).get("mission");
  const [offer,setOffer]=React.useState<DemoOffer|null>(null); const [organization,setOrganization]=React.useState<DemoOrganization|null>(null); const [evidence,setEvidence]=React.useState<DemoEvidence|null>(null); const [mission,setMission]=React.useState<DemoMissionView|null>(null); const [quantity,setQuantity]=React.useState(""); const [error,setError]=React.useState(""); const [busy,setBusy]=React.useState(false);
  const refreshMission=React.useCallback(async()=>{if(missionId)setMission(await demoApi.getMission(missionId));},[missionId]);
  React.useEffect(()=>{if(!params?.offerId)return; void (async()=>{const item=await demoApi.getOffer(params.offerId); setOffer(item); setQuantity(item.minimumQuantity); setOrganization(await demoApi.getOrganization(item.organizationId)); await refreshMission();})();},[params?.offerId,refreshMission]);
  if(!offer)return <div className="p-12 text-center text-slate-500">Loading opportunity…</div>;
  const loadEvidence=async()=>{setEvidence(await demoApi.getEvidence(offer.offerId)); await refreshMission();};
  const submit=async()=>{setBusy(true);setError("");try{const order=await demoApi.createOrder(offer.offerId,quantity);navigate(demoRoutes.order(order.orderId, order.scenarioId));}catch(reason){setError(reason instanceof DemoApiError&&reason.code==="invalid_quantity"?`Quantity must be between ${offer.minimumQuantity} and ${offer.quantity} ${formatUnit(offer.unit)}.`:"The simulated order could not be created.");}finally{setBusy(false);}};
  const notional=Number(quantity)*Number(offer.pricePerUnit);
  return <div className="mx-auto grid max-w-7xl gap-7 px-4 py-10 sm:px-6 lg:grid-cols-[1fr_330px]">
    <div><Link href="/demo/marketplace" className="text-sm text-emerald-700">← Marketplace</Link><section className="mt-5 rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-9"><div className="flex flex-wrap items-center gap-2"><Badge>{offer.side.toUpperCase()}</Badge><Badge variant="outline">{offer.assuranceLabel}</Badge></div><h1 className="mt-5 text-4xl font-semibold">{offer.commodity}</h1><p className="mt-3 flex items-center gap-2 text-slate-500"><MapPin className="h-4 w-4" />{offer.location}</p><div className="mt-8 grid gap-5 border-y border-slate-100 py-6 sm:grid-cols-3"><div><p className="text-sm text-slate-500">Available quantity</p><p className="mt-1 text-lg font-semibold">{Number(offer.quantity).toLocaleString()} {formatUnit(offer.unit)}</p></div><div><p className="text-sm text-slate-500">Price</p><p className="mt-1 text-lg font-semibold">{offer.currency} {Number(offer.pricePerUnit).toLocaleString()}</p></div><div><p className="text-sm text-slate-500">Incoterm</p><p className="mt-1 text-lg font-semibold">{offer.incoterm}</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div><p className="text-sm text-slate-500">Origin</p><p className="font-medium">{offer.origin??"Open"}</p></div><div><p className="text-sm text-slate-500">Destination</p><p className="font-medium">{offer.destination??"Open"}</p></div><div className="sm:col-span-2"><p className="text-sm text-slate-500">Payment terms</p><p className="font-medium">{offer.paymentTerms}</p></div></div></section>
    {organization&&<Card className="mt-6"><CardContent className="flex flex-col justify-between gap-5 p-6 sm:flex-row sm:items-center"><div className="flex gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-100"><Building2 className="h-5 w-5 text-emerald-700" /></div><div><p className="font-semibold">{organization.legalName}</p><p className="text-sm text-slate-500">{organization.jurisdiction} · {organization.sector}</p><div className="mt-2 flex flex-wrap gap-3 text-xs text-emerald-700"><span><CheckCircle2 className="mr-1 inline h-3 w-3"/>Verified</span><span>Trust established</span><span>Eligible</span></div></div></div><Button variant="outline" asChild><Link href={demoRoutes.organization(organization.organizationId)}>View organization</Link></Button></CardContent></Card>}
    <Card className="mt-6"><CardContent className="p-6"><div className="flex items-center gap-3"><FileCheck2 className="h-6 w-6 text-emerald-700"/><h2 className="text-xl font-semibold">Offer evidence</h2></div>{!evidence?<div><p className="mt-3 text-slate-600">Review the evidence assurance supporting this simulated opportunity.</p><Button className="mt-5" variant="outline" onClick={()=>void loadEvidence()}>Review evidence</Button></div>:<div className="mt-5"><div className="rounded-xl bg-emerald-50 p-4"><p className="font-semibold text-emerald-900">{evidence.assuranceLabel}</p><p className="mt-1 text-sm text-emerald-800">{ASSURANCE_COPY[evidence.assuranceLevel]}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(evidence.specifications).map(([key,value])=><div key={key} className="rounded-lg border border-slate-200 p-3"><p className="text-xs capitalize text-slate-500">{key}</p><p className="mt-1 font-medium">{value}</p></div>)}</div><p className="mt-4 text-xs text-slate-500">This scenario presentation does not claim that real external verification or inspection occurred.</p></div>}</CardContent></Card>
    <Card className="mt-6"><CardContent className="p-6"><h2 className="text-xl font-semibold">Place simulated order</h2><p className="mt-2 text-sm text-slate-600">This order is part of the TUTELA interactive simulation and creates no binding commercial obligation.</p><div className="mt-5 grid gap-4 sm:grid-cols-[1fr_1fr_auto]"><div><label className="text-sm text-slate-500">Quantity ({formatUnit(offer.unit)})</label><Input value={quantity} onChange={(e)=>setQuantity(e.target.value)} /></div><div><p className="text-sm text-slate-500">Estimated notional</p><p className="mt-2 font-semibold">{Number.isFinite(notional)?`${offer.currency} ${notional.toLocaleString(undefined,{maximumFractionDigits:2})}`:"—"}</p></div><Button disabled={!evidence||busy} className="self-end" onClick={()=>void submit()}>{busy?"Submitting…":"Submit order"}<ArrowRight className="ml-2 h-4 w-4"/></Button></div>{!evidence&&<p className="mt-3 text-xs text-amber-700">Review evidence before placing the simulated order.</p>}{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</CardContent></Card></div>
    <div>{mission?<GuidedProgress mission={mission} onExit={()=>navigate("/demo/marketplace")}/>:<div className="rounded-2xl border border-slate-200 bg-white p-5"><ShieldCheck className="h-6 w-6 text-emerald-700"/><p className="mt-3 font-semibold">Simulation assurance</p><p className="mt-2 text-sm text-slate-600">Production APIs and data are never used by this demo journey.</p></div>}</div>
  </div>;
}
