import React from "react";
import { Link, useLocation, useRoute } from "wouter";
import { CheckCircle2, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { demoApi } from "@/features/demo/api";
import { useDemoSession } from "@/features/demo/DemoContext";
import { formatUnit } from "@/features/demo/presentation";
import type { DemoContract, DemoMissionView, DemoOffer, DemoOrganization } from "@/features/demo/types";

export default function DemoContractPage() {
  const [,params]=useRoute("/demo/contracts/:contractId"); const [,navigate]=useLocation(); const {session,reset}=useDemoSession();
  const [contract,setContract]=React.useState<DemoContract|null>(null); const [offer,setOffer]=React.useState<DemoOffer|null>(null); const [counterparty,setCounterparty]=React.useState<DemoOrganization|null>(null); const [mission,setMission]=React.useState<DemoMissionView|null>(null);
  React.useEffect(()=>{if(!params?.contractId)return;void(async()=>{const value=await demoApi.getContract(params.contractId);setContract(value);const item=await demoApi.getOffer(value.offerId);setOffer(item);setCounterparty(await demoApi.getOrganization(item.organizationId));setMission(await demoApi.getMission(value.scenarioId).catch(()=>null));})();},[params?.contractId]);
  if(!contract||!offer||!session)return <div className="p-12 text-center text-slate-500">Loading contract preview…</div>;
  const participantId=`demo:org:session-${session.demoSessionId.slice("demo:session:".length)}`; const party=(id:string)=>id===participantId?session.visitor.company:(counterparty?.legalName??"Synthetic counterparty");
  const resetAll=async()=>{await reset();navigate("/demo");};
  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><div className="rounded-2xl bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto h-9 w-9 text-emerald-700"/><h1 className="mt-3 text-3xl font-semibold">Trade simulation complete</h1><p className="mx-auto mt-3 max-w-2xl text-slate-600">You've completed a simulated TUTELA transaction from verified marketplace opportunity through order acceptance and contract generation.</p></div>
    <Card className="relative mt-8 overflow-hidden"><div className="pointer-events-none absolute inset-0 grid place-items-center overflow-hidden"><span className="rotate-[-28deg] whitespace-nowrap text-5xl font-bold tracking-widest text-slate-100 sm:text-7xl">SIMULATION — NON-BINDING</span></div><CardContent className="relative p-7 sm:p-10"><div className="flex flex-col justify-between gap-4 border-b border-slate-200 pb-6 sm:flex-row"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Trade contract preview</p><h2 className="mt-2 text-2xl font-semibold">{offer.commodity}</h2></div><div className="text-sm sm:text-right"><p className="text-slate-500">Contract reference</p><p className="font-mono font-medium">{contract.contractId}</p></div></div><dl className="mt-7 grid gap-x-8 gap-y-5 sm:grid-cols-2">{[["Buyer",party(contract.buyerOrganizationId)],["Seller",party(contract.sellerOrganizationId)],["Commodity",offer.commodity],["Quantity",`${Number(contract.quantity).toLocaleString()} ${formatUnit(contract.unit)}`],["Unit price",`${contract.currency} ${Number(contract.pricePerUnit).toLocaleString()}`],["Total amount",`${contract.currency} ${Number(contract.totalAmount).toLocaleString()}`],["Delivery terms",`${offer.incoterm} · ${offer.location}`],["Payment terms",offer.paymentTerms],["Order reference",contract.orderId],["Created",new Date(contract.createdAt).toLocaleString()]].map(([label,value])=><div key={label}><dt className="text-sm text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl><div className="mt-8 rounded-xl border-2 border-amber-300 bg-amber-50 p-4 text-center font-bold tracking-wider text-amber-950">{contract.legalMarker}</div><p className="mt-4 text-center text-xs text-slate-500">No signatures, payment, escrow, blockchain execution, or legal signing are included in this simulation.</p></CardContent></Card>
    <div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild><Link href="/demo/marketplace">Explore marketplace</Link></Button><Button variant="outline" asChild><Link href="/demo/missions">Try another guided scenario</Link></Button><Button variant="ghost" onClick={()=>void resetAll()}><RotateCcw className="mr-2 h-4 w-4"/>Reset demo</Button></div>{mission?.progress?.completionState==="completed"&&<p className="mt-5 text-center text-sm font-medium text-emerald-700">All guided steps completed from server-recorded progress.</p>}</div>;
}
