import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { apiRequest,getQueryFn } from "@/lib/queryClient";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
type Order={orderId:string;offerId:string;buyerUserId:string;sellerUserId:string;status:"created"|"accepted"|"cancelled";orderVersion:number;createdAt:string;acceptedAt:string|null;orderFingerprint:string;terms:{quantity:string;unit:string;pricePerUnit:string;totalAmount:string;currency:string}};
export default function Orders(){const auth=useAuth(),query=useQueryClient(),{toast}=useToast();const{data=[],isLoading}=useQuery<Order[]>({queryKey:["/api/orders"],queryFn:getQueryFn({on401:"throw"})});
  const accept=useMutation({mutationFn:(id:string)=>apiRequest("PATCH",`/api/orders/${id}/status`,{status:"accepted"}),onSuccess:()=>query.invalidateQueries({queryKey:["/api/orders"]}),onError:(e)=>toast({title:"Order not accepted",description:e instanceof Error?e.message:"The current authority checks did not pass.",variant:"destructive"})});
  const contract=useMutation({mutationFn:(orderId:string)=>apiRequest("POST","/api/contracts",{orderId}),onSuccess:async()=>{await Promise.all([query.invalidateQueries({queryKey:["/api/orders"]}),query.invalidateQueries({queryKey:["/api/contracts"]})]);toast({title:"Contract draft created",description:"The immutable Current V2 contract snapshot is available in Contracts."});},onError:(e)=>toast({title:"Contract not created",description:e instanceof Error?e.message:"An accepted authoritative order is required.",variant:"destructive"})});
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Orders</h1><p className="text-sm text-neutral-600">Current V2 orders derived from published offers. No payment, shipping, or settlement status is implied.</p></div>{isLoading?<p>Loading orders…</p>:data.length===0?<Card><CardContent className="py-8 text-sm text-neutral-600">No authoritative orders yet. Eligible buyers create an order from a published Marketplace offer.</CardContent></Card>:<div className="grid gap-4">{data.map(order=>{const seller=auth.user?.id===order.sellerUserId,participant=seller||auth.user?.id===order.buyerUserId;return <Card key={order.orderId}><CardHeader><CardTitle className="text-lg">{order.terms.quantity} {order.terms.unit} · {order.terms.totalAmount} {order.terms.currency}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>Status: <strong>{order.status}</strong> · version {order.orderVersion}</p><p>Unit price: {order.terms.pricePerUnit} {order.terms.currency}</p><p className="break-all text-xs text-neutral-500">Order {order.orderId} · Offer {order.offerId}</p>{seller&&order.status==="created"&&<Button disabled={accept.isPending} onClick={()=>accept.mutate(order.orderId)}>Accept current order</Button>}{participant&&order.status==="accepted"&&<Button variant="outline" disabled={contract.isPending} onClick={()=>contract.mutate(order.orderId)}>Create V2 contract draft</Button>}</CardContent></Card>})}</div>}</div>;
}
