import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Building2, Globe2, ShieldCheck, Users, KeyRound, ScrollText, History } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { TotpCodeInput } from "@/components/security/TotpCodeInput";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useOrganizationContext } from "@/hooks/useOrganizationContext";

type Workspace = {
  organizationId:string; profile:any; team:any[]; membershipRequests:any[]; verifiedDomains:any[]; membershipPolicy:any;
  capabilityGrants:any[]; signingMandates:any[]; signingPolicy:any; auditActivity:any[];
};
const title=(profile:any)=>profile?.legal_identity_projection?.legal_name??"Current organization";
const format=(value:unknown)=>value?new Date(String(value)).toLocaleString():"—";

export default function OrganizationWorkspace(){
  const context=useOrganizationContext();const organization=context.context?.state==="available"?context.context.organization:null;
  const id=organization?.organizationId;
  const workspace=useQuery<Workspace>({queryKey:[`/api/organizations/${id}/workspace`],enabled:Boolean(id)});
  const[email,setEmail]=useState("");const[domain,setDomain]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  const[inviteLink,setInviteLink]=useState("");
  const[mandateUser,setMandateUser]=useState("");const[mandateLimit,setMandateLimit]=useState("");const[mandateCurrency,setMandateCurrency]=useState("USD");const[totp,setTotp]=useState("");const[stepUp,setStepUp]=useState(false);
  async function mutate(url:string,payload:unknown){setBusy(true);setMessage("");try{await apiRequest("POST",url,payload);await queryClient.invalidateQueries({queryKey:[`/api/organizations/${id}/workspace`]});setMessage("Saved. The new item is governed by server authority.");}catch{setMessage("The request could not be completed. Check your authority and try again.");}finally{setBusy(false)}}
  async function verifyStepUp(){setBusy(true);setMessage("");try{await apiRequest("POST","/api/auth/mfa/step-up",{code:totp});setTotp("");setStepUp(true);setMessage("Privileged step-up verified. You may now submit the scoped mandate.");}catch{setMessage("The code could not be verified. Wait for a new authenticator code and try again.");}finally{setBusy(false)}}
  async function grantMandate(){if(!id||!mandateUser)return;await mutate(`/api/organizations/${id}/signing-mandates`,{userId:mandateUser,actionScope:["contract.sign"],contractTypeScope:["tutela-international-commodity-sale-contract/v1.1"],signatureEligibility:"INDIVIDUAL",validFrom:new Date().toISOString(),reason:"Organization owner granted an explicit scoped contract-signing mandate",...(mandateLimit?{maximumTransactionValue:mandateLimit,valueCurrency:mandateCurrency}: {})});setStepUp(false);setMandateLimit("");}
  async function decide(requestId:string,decision:"APPROVED"|"REJECTED"){await mutate(`/api/organizations/${id}/membership-requests/${requestId}/decision`,{decision,reason:`Organization owner ${decision.toLowerCase()} the membership request`})}
  async function createInvitation(){if(!id)return;setBusy(true);setMessage("");setInviteLink("");try{const response=await apiRequest("POST",`/api/organizations/${id}/invitations`,{email,expiresInHours:72});const result=await response.json();setInviteLink(`${window.location.origin}/organization/setup?invitation=${encodeURIComponent(result.token)}`);setEmail("");setMessage("Invitation created. Share the private link with the named recipient only; it expires in 72 hours.");}catch{setMessage("The invitation could not be created. Check your authority and try again.");}finally{setBusy(false)}}
  if(!id)return <Card><CardHeader><CardTitle>Organization setup required</CardTitle><CardDescription>Resolve, join, or register an organization before opening this workspace.</CardDescription></CardHeader></Card>;
  if(workspace.isLoading)return <p className="p-6 text-sm text-neutral-600">Loading organization workspace…</p>;
  if(!workspace.data)return <Card><CardHeader><CardTitle>Organization workspace unavailable</CardTitle><CardDescription>No authority state has been changed.</CardDescription></CardHeader></Card>;
  const data=workspace.data,profile=data.profile?.legal_identity_projection??{};
  return <div className="space-y-6" data-testid="organization-workspace">
    <div className="rounded-2xl bg-gradient-to-r from-emerald-950 to-emerald-800 p-6 text-white"><div className="flex items-center gap-3"><Building2 className="h-8 w-8"/><div><p className="text-sm text-emerald-100">Current organization</p><h1 className="text-2xl font-semibold">{title(data.profile)}</h1><p className="text-sm text-emerald-100">{profile.registration_jurisdiction??data.profile?.jurisdiction} · {organization.membership.role}</p></div></div></div>
    {message&&<p role="status" className="rounded-lg border bg-white p-3 text-sm">{message}</p>}
    <div className="grid gap-5 xl:grid-cols-2">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/>Overview & verification</CardTitle><CardDescription>Canonical status comes from the verification and trust engines.</CardDescription></CardHeader><CardContent className="grid gap-2 text-sm"><p><b>Verification:</b> {organization.verification.phase.replaceAll("_"," ")}</p><p><b>Trust:</b> {organization.verification.canonicalTrustStatus??"Not established"}</p><p><b>Profile revision:</b> {organization.profileRevisionId}</p></CardContent></Card>
      <Card><CardHeader><CardTitle>Company profile</CardTitle><CardDescription>Registry profile; edits do not silently rewrite earlier revisions.</CardDescription></CardHeader><CardContent className="text-sm"><p><b>Legal name:</b> {profile.legal_name}</p><p><b>Jurisdiction:</b> {profile.registration_jurisdiction}</p><p><b>Trading names:</b> {(profile.trading_names??[]).join(", ")||"None recorded"}</p></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5"/>Team</CardTitle><CardDescription>Membership is distinct from capabilities and signing mandates.</CardDescription></CardHeader><CardContent className="space-y-3">{data.team.map(member=><div key={member.membership_id} className="rounded-lg border p-3 text-sm"><p className="font-medium">{member.display_name||member.email}</p><p className="text-neutral-600">{member.email} · {member.role} · {member.status}</p></div>)}{organization.membership.role==="owner"&&data.membershipRequests.map(request=><div key={request.request_id} className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm"><p className="font-medium">Membership request</p><p className="text-neutral-700">{request.normalized_email} · {request.resolution_basis.replaceAll("_"," ")}</p><div className="mt-2 flex gap-2"><Button type="button" size="sm" disabled={busy} onClick={()=>void decide(request.request_id,"APPROVED")}>Approve as Member</Button><Button type="button" size="sm" variant="outline" disabled={busy} onClick={()=>void decide(request.request_id,"REJECTED")}>Reject</Button></div></div>)}<form className="flex gap-2" onSubmit={e=>{e.preventDefault();void createInvitation()}}><Input aria-label="Invitee business email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com" required/><Button disabled={busy}>Invite member</Button></form>{inviteLink&&<div className="rounded-lg border bg-neutral-50 p-3 text-sm"><Label htmlFor="invitation-link">Private one-time invitation link</Label><Input id="invitation-link" className="mt-1" readOnly value={inviteLink} onFocus={event=>event.currentTarget.select()}/></div>}<p className="text-xs text-neutral-500">Invitations bind one verified email, expire, and can be redeemed once. They grant basic Member only. TUTELA stores only the token digest.</p></CardContent></Card>
      <Card><CardHeader><CardTitle>Roles & permissions</CardTitle><CardDescription>Operational capabilities are explicit grants, never inferred from email or title.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm">{data.capabilityGrants.length?data.capabilityGrants.map(grant=><div key={grant.capability_grant_id} className="rounded-lg border p-3"><b>{grant.capability}</b><p className="text-neutral-600">User {grant.user_id} · {grant.active?"active":"revoked"}</p></div>):<p className="text-neutral-600">No delegated capabilities. Organization owners retain existing governance authority.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5"/>Signing authority</CardTitle><CardDescription>Mandates are scoped and remain subject to active membership, exact contract version, consent, MFA and VRE gates.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm">{data.signingMandates.length?data.signingMandates.map(m=><div key={m.mandate_id} className="rounded-lg border p-3"><p className="font-medium">{m.signature_eligibility} mandate</p><p className="text-neutral-600">Actions: {m.action_scope.join(", ")} · Valid until {format(m.valid_until)}</p><div className="mt-2 flex items-center justify-between"><p>{m.active?"Active record":"Revoked"}</p>{m.active&&organization.membership.role==="owner"&&stepUp&&<Button type="button" size="sm" variant="destructive" disabled={busy} onClick={()=>void mutate(`/api/organizations/${id}/signing-mandates/${m.mandate_id}/revoke`,{reason:"Organization owner revoked the signing mandate"}).then(()=>setStepUp(false))}>Revoke mandate</Button>}</div></div>):<p className="text-neutral-600">No scoped mandates. Explicit historical signing authorities remain under the compatibility policy.</p>}{organization.membership.role==="owner"&&<div className="space-y-3 rounded-xl border bg-neutral-50 p-3"><p className="font-semibold">Grant an individual sale-contract mandate</p><Label htmlFor="mandate-member">Active member</Label><select id="mandate-member" className="h-10 w-full rounded-md border bg-white px-3" value={mandateUser} onChange={event=>setMandateUser(event.target.value)}><option value="">Select a member</option>{data.team.filter(member=>member.status==="active").map(member=><option key={member.user_id} value={member.user_id}>{member.display_name||member.email}</option>)}</select><div className="grid grid-cols-[1fr_90px] gap-2"><Input aria-label="Optional maximum transaction value" inputMode="decimal" placeholder="Optional value limit" value={mandateLimit} onChange={event=>setMandateLimit(event.target.value.replace(/[^0-9.]/g,""))}/><Input aria-label="Value currency" maxLength={3} value={mandateCurrency} onChange={event=>setMandateCurrency(event.target.value.toUpperCase())}/></div>{!stepUp?<><TotpCodeInput label="Current authenticator code" value={totp} onChange={setTotp}/><Button type="button" variant="outline" disabled={busy||!/^[0-9]{6}$/.test(totp)} onClick={()=>void verifyStepUp()}>Verify privileged step-up</Button></>:<Button type="button" disabled={busy||!mandateUser||Boolean(mandateLimit&&!/^\d+(?:\.\d{1,8})?$/.test(mandateLimit))||!/^([A-Z]{3})$/.test(mandateCurrency)} onClick={()=>void grantMandate()}>Grant scoped mandate</Button>}<p className="text-xs text-neutral-500">A job title is not authority. This creates an auditable mandate for Contract V1.1 signing only.</p></div>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><ScrollText className="h-5 w-5"/>Signing policy</CardTitle><CardDescription>A policy determines required signature slots; a mandate determines signer eligibility.</CardDescription></CardHeader><CardContent className="text-sm"><p><b>{data.signingPolicy.policy_kind??data.signingPolicy.policyKind}</b></p><p className="mt-2 text-neutral-600">{data.signingPolicy.compatibilityDefault?"Explicit compatibility default: one authorized signer per party.":"Versioned organization policy is active."}</p></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Globe2 className="h-5 w-5"/>Verified domains</CardTitle><CardDescription>A requested domain stays Pending until a real governed verification method confirms it.</CardDescription></CardHeader><CardContent className="space-y-3">{data.verifiedDomains.map(d=><div key={d.domain_id} className="rounded-lg border p-3 text-sm"><b>{d.normalized_domain}</b><p className="text-neutral-600">{d.status} · {d.verification_method}</p></div>)}<form className="space-y-2" onSubmit={e=>{e.preventDefault();void mutate(`/api/organizations/${id}/domains`,{domain,verificationMethod:"DNS_CHALLENGE",reason:"Organization requested DNS verification"}).then(()=>setDomain(""))}}><Label htmlFor="org-domain">Company domain</Label><div className="flex gap-2"><Input id="org-domain" value={domain} onChange={e=>setDomain(e.target.value)} placeholder="company.com" required/><Button variant="outline" disabled={busy}>Request verification</Button></div></form></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><History className="h-5 w-5"/>Audit activity</CardTitle><CardDescription>Recent organization-authority events.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm">{data.auditActivity.length?data.auditActivity.map((item,index)=><div key={`${item.subject_reference}-${index}`} className="border-b pb-2"><p className="font-medium">{item.event_type.replaceAll("_"," ")}</p><p className="text-neutral-500">{format(item.occurred_at)}</p></div>):<p className="text-neutral-600">No Delta A authority events recorded yet.</p>}</CardContent></Card>
    </div>
  </div>;
}
