export const ORGANIZATION_VERIFICATION_IDENTITY_LINEAGE = Object.freeze([
  Object.freeze({
    order: 1,
    identity: "organization_id",
    owner: "organization_registry",
    boundBy: "OrganizationVerificationRecord.organizationId",
    parentIdentity: undefined,
    required: true,
    consumers: Object.freeze([
      "organization_verification_domain",
      "workflow_contract",
      "persistence_contract",
      "replay_runtime",
      "application_service_contract",
    ]),
    forbiddenCompetingOwners: Object.freeze([
      "workflow_runtime",
      "persistence_adapter",
      "replay_runtime",
      "application_service_runtime",
    ]),
  }),
  Object.freeze({
    order: 2,
    identity: "record_id",
    owner: "organization_verification_domain",
    boundBy: "OrganizationVerificationRevision.recordId",
    parentIdentity: "organization_id",
    required: true,
    consumers: Object.freeze([
      "attempt_lifecycle_contract",
      "workflow_contract",
      "persistence_contract",
      "replay_runtime",
      "application_service_contract",
    ]),
    forbiddenCompetingOwners: Object.freeze([
      "workflow_runtime",
      "persistence_adapter",
      "replay_runtime",
      "application_service_runtime",
    ]),
  }),
  Object.freeze({
    order: 3,
    identity: "revision_id",
    owner: "organization_verification_domain",
    boundBy: "OrganizationVerificationAttempt.revisionId",
    parentIdentity: "record_id",
    required: true,
    consumers: Object.freeze([
      "attempt_lifecycle_contract",
      "workflow_contract",
      "persistence_contract",
      "replay_runtime",
      "application_service_contract",
    ]),
    forbiddenCompetingOwners: Object.freeze([
      "workflow_runtime",
      "persistence_adapter",
      "replay_runtime",
      "application_service_runtime",
    ]),
  }),
  Object.freeze({
    order: 4,
    identity: "attempt_id",
    owner: "organization_verification_domain",
    boundBy: "OrganizationVerificationWorkflowExecution.attemptId",
    parentIdentity: "revision_id",
    required: true,
    consumers: Object.freeze([
      "attempt_lifecycle_contract",
      "workflow_contract",
      "persistence_contract",
      "replay_runtime",
      "application_service_contract",
    ]),
    forbiddenCompetingOwners: Object.freeze([
      "workflow_runtime",
      "persistence_adapter",
      "replay_runtime",
      "application_service_runtime",
    ]),
  }),
  Object.freeze({
    order: 5,
    identity: "workflow_execution_id",
    owner: "workflow_contract",
    boundBy: "OrganizationVerificationWorkflowStreamIdentity.workflowExecutionId",
    parentIdentity: "attempt_id",
    required: true,
    consumers: Object.freeze([
      "workflow_runtime",
      "persistence_contract",
      "replay_runtime",
      "application_service_contract",
    ]),
    forbiddenCompetingOwners: Object.freeze([
      "persistence_adapter",
      "replay_runtime",
      "application_service_runtime",
    ]),
  }),
  Object.freeze({
    order: 6,
    identity: "persistence_stream_identity",
    owner: "persistence_contract",
    boundBy: "OrganizationVerificationReplayExecution.streamIdentity",
    parentIdentity: "workflow_execution_id",
    required: true,
    consumers: Object.freeze([
      "persistence_adapter",
      "replay_runtime",
      "application_service_contract",
      "application_service_runtime",
    ]),
    forbiddenCompetingOwners: Object.freeze([
      "workflow_runtime",
      "replay_runtime",
      "application_service_runtime",
    ]),
  }),
  Object.freeze({
    order: 7,
    identity: "replay_request_id",
    owner: "application_service_contract",
    suppliedBy: "application_service_caller",
    boundBy: "OrganizationVerificationReplayRequest.replayRequestId",
    parentIdentity: "persistence_stream_identity",
    required: true,
    consumers: Object.freeze([
      "replay_runtime",
      "application_service_runtime",
    ]),
    forbiddenCompetingOwners: Object.freeze([
      "persistence_adapter",
      "workflow_runtime",
      "replay_runtime",
      "application_service_runtime",
    ]),
  }),
  Object.freeze({
    order: 8,
    identity: "replay_execution_id",
    owner: "application_service_contract",
    suppliedBy: "application_service_caller",
    boundBy: "OrganizationVerificationReplayRequest.replayExecutionId",
    parentIdentity: "replay_request_id",
    required: true,
    consumers: Object.freeze([
      "replay_runtime",
      "application_service_contract",
      "application_service_runtime",
    ]),
    forbiddenCompetingOwners: Object.freeze([
      "persistence_adapter",
      "workflow_runtime",
      "replay_runtime",
      "application_service_runtime",
    ]),
  }),
  Object.freeze({
    order: 9,
    identity: "application_request_identity",
    owner: "application_service_contract",
    boundBy: "OrganizationVerificationApplicationExecution.requestIdentity",
    parentIdentity: undefined,
    required: true,
    consumers: Object.freeze([
      "application_service_runtime",
      "future_delivery_layer",
    ]),
    forbiddenCompetingOwners: Object.freeze([
      "future_delivery_layer",
      "replay_runtime",
      "persistence_adapter",
      "workflow_runtime",
    ]),
  }),
  Object.freeze({
    order: 10,
    identity: "application_execution_id",
    owner: "application_service_contract",
    boundBy: "OrganizationVerificationApplicationExecution.applicationExecutionId",
    parentIdentity: "application_request_identity",
    required: true,
    consumers: Object.freeze([
      "application_service_runtime",
      "future_delivery_layer",
    ]),
    forbiddenCompetingOwners: Object.freeze([
      "future_delivery_layer",
      "replay_runtime",
      "persistence_adapter",
      "workflow_runtime",
    ]),
  }),
] as const);

export type OrganizationVerificationIdentityLineageEntry =
  (typeof ORGANIZATION_VERIFICATION_IDENTITY_LINEAGE)[number];
