import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read=(path:string)=>readFileSync(path,"utf8");
test("MVP closure APIs derive actor identity and organization authority server-side",()=>{const routes=read("server/mvp-closure/routes.ts"),service=read("server/mvp-closure/service.ts");assert.match(routes,/req\.user\?\.claims\?\.sub/);assert.doesNotMatch(routes,/body\?\.(?:organizationId|signerUserId|actorUserId)/);assert.match(service,/organization_memberships/);assert.match(service,/status='active'/)});
test("signing is exact-version, step-up protected and cannot be fabricated by Admin",()=>{const routes=read("server/mvp-closure/routes.ts"),service=read("server/mvp-closure/service.ts"),main=read("server/routes.ts");assert.match(routes,/hasRecentStepUp/);assert.match(service,/previewDocumentSha256/);assert.match(service,/session_assurance/);assert.doesNotMatch(main,/admin.*sign\(/s);assert.match(main,/getForAdmin/)});
test("PDF generation is downstream of immutable snapshot authority",()=>{const migration=read("migrations/0024_mvp_transaction_closure.sql"),document=read("server/mvp-closure/contractDocument.ts");assert.match(migration,/mvp_contract_snapshot_immutable/);assert.match(migration,/mvp_contract_artifact_immutable/);assert.match(document,/PDF generation does not itself form, amend or execute/);assert.doesNotMatch(document,/Official ICC Contract|ICC Model Contract/)});
test("execution evidence remains an assertion and closeout is append-only",()=>{const migration=read("migrations/0024_mvp_transaction_closure.sql"),service=read("server/mvp-closure/service.ts");assert.match(migration,/EVIDENCE_IS_NOT_VERIFIED_TRUTH/);assert.match(migration,/mvp_contract_event_immutable/);assert.match(service,/dispute_blocks_closeout/)});
test("seller acceptance takes an offer lock before a fresh allocation statement",()=>{const repository=read("server/trading-flow/postgresRepository.ts");const lock=repository.indexOf("FOR UPDATE OF offer"),allocation=repository.indexOf("WITH allocated AS MATERIALIZED",lock);assert.ok(lock>0);assert.ok(allocation>lock);assert.match(repository,/allocated\.allocated_quantity\+candidate\.quantity<=\$7::numeric/)});
