import { createHash } from "node:crypto";

export const MVP_TEMPLATE_VERSION = "tutela-international-commodity-sale-contract/v1.1" as const;
export const CONTRACT_READINESS_POLICY_VERSION = "tutela-contract-readiness/v1.1" as const;
export const UREA46_PROFILE_VERSION = "tutela-commodity-profile/urea46/v1.1" as const;
export const GENERAL_PROFILE_VERSION = "tutela-commodity-profile/general/v1.1" as const;
export const INCOTERMS_2020 = ["EXW","FCA","CPT","CIP","DAP","DPU","DDP","FAS","FOB","CFR","CIF"] as const;
export type Incoterm2020 = typeof INCOTERMS_2020[number];
export type ContractParty = "SELLER" | "BUYER";
export type CisgTreatment = "APPLIES_WHERE_LEGALLY_APPLICABLE" | "EXPRESSLY_INCLUDED" | "EXPRESSLY_EXCLUDED" | "LEGAL_REVIEW_REQUIRED";
export type MvpContractState = "CONTRACT_PREPARATION" | "CONTRACT_READY" | "AWAITING_SELLER_SIGNATURE" | "AWAITING_BUYER_SIGNATURE" | "EXECUTED" | "EXECUTION_STARTED" | "DOCUMENTS_SUBMITTED" | "DELIVERY_CONFIRMED" | "SETTLEMENT_CONFIRMED" | "TRADE_CLOSED" | "DISPUTED" | "TERMINATED";

export interface LegalPartySnapshot {
  readonly organizationId:string;readonly profileRevisionId:string;readonly legalName:string;readonly registrationJurisdiction:string;
  readonly registrationIdentifiers:readonly Readonly<{scheme:string;value:string}>[];
  readonly registeredAddress:Readonly<{countryCode?:string;administrativeArea?:string;locality?:string;postalCode?:string;addressLines?:readonly string[]}>;
  readonly commercialRepresentative:string;readonly authorizedSignatory:string;
  /** Historical V1 compatibility only. */ readonly authorizedRepresentative?:string;
}
export interface SpecificationLine {readonly code:string;readonly label:string;readonly value:string;readonly unit?:string;readonly tolerance?:string;readonly sourceReference:string}
export interface ContractTermsSnapshot {
  readonly contractId:string;readonly orderId:string;readonly tutelaReference:string;readonly contractVersion:number;readonly snapshotId:string;readonly snapshotCreatedAt:string;
  readonly preparedAt:string;readonly effectiveDate:string|null;readonly templateVersion:typeof MVP_TEMPLATE_VERSION;readonly commercialProfileVersion:string;
  readonly seller:LegalPartySnapshot;readonly buyer:LegalPartySnapshot;
  readonly commodity:Readonly<{name:string;grade:string;form:string;productDescription:string;origin:string;producer?:string;customsClassification?:Readonly<{scheme:string;code:string;applicabilityBasis:string}>;specifications:readonly SpecificationLine[]}>;
  readonly quantity:Readonly<{amount:string;unit:string;tolerancePercent:string;measurementBasis:string}>;
  readonly price:Readonly<{unitPrice:string;currency:string;pricingBasis:string;estimatedTotal:string}>;
  readonly delivery:Readonly<{incoterm:Incoterm2020;incotermsVersion:"2020";namedPlace:string;shipmentWindowStart:string;shipmentWindowEnd:string;laycanSemantics:string;packaging:string;shipmentMode:string;partialShipmentPolicy:"ALLOWED"|"NOT_ALLOWED"|"BY_WRITTEN_AGREEMENT"}>;
  readonly inspection:Readonly<{required:boolean;bodyOrMethod:string;inspectionPoint:string;quantityDetermination:string;qualityDetermination:string;finalityAndClaims:string;claimsNoticePeriod:string}>;
  readonly payment:Readonly<{method:string;methodCode:"OPEN_ACCOUNT"|"ADVANCE"|"DOCUMENTARY_COLLECTION"|"LETTER_OF_CREDIT"|"OTHER";timing:string;dueTrigger:string;currency:string;bankDocumentConditions:string}>;
  readonly requiredDocuments:readonly string[];
  readonly legal:Readonly<{riskTransfer:string;titleTransfer:string;governingLaw:string;cisgTreatment:CisgTreatment;disputeResolution:"ICC_ARBITRATION"|"COURTS";arbitrationInstitution?:"ICC";arbitrationSeat?:string;arbitrationLanguage?:string;arbitratorCount?:1|3;forceMajeureTreatment:string;hardshipTreatment:string;claimsTreatment:string;defaultTreatment:string;liabilityTreatment:string;tradeComplianceTreatment:string}>;
  readonly platform:Readonly<{platformRole:string;platformFeeTreatment:string;snapshotVersion:1;sourceOrderFingerprint:string;sourceTermsFingerprint:string}>;readonly specialConditions:readonly string[];
}
export interface ReadinessResult {readonly outcome:"READY"|"NOT_READY";readonly missing:readonly string[];readonly presentationPercent:number;readonly applicableRequirementCount:number;readonly satisfiedRequirementCount:number;readonly policyVersion:typeof CONTRACT_READINESS_POLICY_VERSION}
export interface CommodityContractProfile {readonly profileVersion:string;readonly allowedUnits:readonly string[];readonly requiredSpecificationCodes:readonly string[];readonly requiredDocuments:readonly string[];readonly customsClassificationRequired:boolean}
const PROFILES:Readonly<Record<string,CommodityContractProfile>>=Object.freeze({
  [UREA46_PROFILE_VERSION]:Object.freeze({profileVersion:UREA46_PROFILE_VERSION,allowedUnits:Object.freeze(["MT","kg","bag"]),requiredSpecificationCodes:Object.freeze(["NITROGEN","BIURET","MOISTURE","PARTICLE_SIZE","APPEARANCE"]),requiredDocuments:Object.freeze(["COMMERCIAL_INVOICE","BILL_OF_LADING","CERTIFICATE_OF_ORIGIN","QUALITY_CERTIFICATE","QUANTITY_CERTIFICATE","PACKING_LIST"]),customsClassificationRequired:false}),
  [GENERAL_PROFILE_VERSION]:Object.freeze({profileVersion:GENERAL_PROFILE_VERSION,allowedUnits:Object.freeze([]),requiredSpecificationCodes:Object.freeze([]),requiredDocuments:Object.freeze(["COMMERCIAL_INVOICE"]),customsClassificationRequired:false}),
});
export function contractProfile(version:string):CommodityContractProfile{return PROFILES[version]??Object.freeze({profileVersion:version,allowedUnits:Object.freeze([]),requiredSpecificationCodes:Object.freeze([]),requiredDocuments:Object.freeze(["COMMERCIAL_INVOICE"]),customsClassificationRequired:false})}

function canonical(value:unknown):string{if(Array.isArray(value))return `[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`;return JSON.stringify(value)}
export function sha256(value:unknown):string{return `sha256:${createHash("sha256").update(typeof value==="string"||Buffer.isBuffer(value)?value:canonical(value)).digest("hex")}`}
const PLACEHOLDER=/^(?:tbd|tbc|to be agreed|mutually agreed|to be confirmed|pending|unknown|n\/?a|not specified)$/i;
const text=(value:unknown,max=2000)=>typeof value==="string"&&value.trim().length>0&&value.trim().length<=max&&!PLACEHOLDER.test(value.trim());
const iso=(value:unknown)=>text(value,40)&&Number.isFinite(Date.parse(value as string));
const positive=(value:unknown)=>typeof value==="string"&&/^\d+(?:\.\d+)?$/.test(value)&&Number(value)>0&&Number.isFinite(Number(value));
const tolerance=(value:unknown)=>typeof value==="string"&&/^\d+(?:\.\d+)?$/.test(value)&&Number(value)>=0&&Number(value)<=100;
const documentCode=(value:string)=>value.trim().toUpperCase().replace(/[^A-Z0-9]+/g,"_").replace(/^_|_$/g,"");

export function evaluateContractReadiness(snapshot:ContractTermsSnapshot):ReadinessResult{
  const missing:string[]=[];let applicable=0,satisfied=0;const require=(condition:boolean,code:string)=>{applicable++;if(condition)satisfied++;else missing.push(code)};const profile=contractProfile(snapshot.commercialProfileVersion);
  require(iso(snapshot.preparedAt),"contract.prepared_at");require(snapshot.effectiveDate===null||iso(snapshot.effectiveDate),"contract.effective_date");
  for(const [party,value] of [["seller",snapshot.seller],["buyer",snapshot.buyer]] as const){require(text(value.legalName),`${party}.legal_name`);require(text(value.registrationJurisdiction),`${party}.registration_jurisdiction`);require(value.registrationIdentifiers.length>0&&value.registrationIdentifiers.every(v=>text(v.scheme)&&text(v.value)),`${party}.registration_identifier`);require(Boolean(value.registeredAddress.countryCode&&value.registeredAddress.locality&&value.registeredAddress.addressLines?.every(v=>text(v))),`${party}.registered_address`);require(text(value.commercialRepresentative),`${party}.commercial_representative`);require(text(value.authorizedSignatory),`${party}.authorized_signatory`)}
  require(text(snapshot.commodity.name),"commodity.name");require(text(snapshot.commodity.grade),"commodity.grade");require(text(snapshot.commodity.form),"commodity.form");require(text(snapshot.commodity.productDescription),"commodity.product_description");require(text(snapshot.commodity.origin),"commodity.origin");require(snapshot.commodity.specifications.length>0,"commodity.specifications");
  for(const line of snapshot.commodity.specifications)require([line.code,line.label,line.value,line.sourceReference].every(v=>text(v)),`specification.${line.code||"unknown"}`);const specCodes=new Set(snapshot.commodity.specifications.map(v=>v.code.toUpperCase()));for(const code of profile.requiredSpecificationCodes)require(specCodes.has(code),`profile.specification.${code.toLowerCase()}`);
  if(profile.customsClassificationRequired)require(Boolean(snapshot.commodity.customsClassification&&text(snapshot.commodity.customsClassification.code)&&text(snapshot.commodity.customsClassification.applicabilityBasis)),"commodity.customs_classification");
  require(positive(snapshot.quantity.amount),"quantity.amount");require(text(snapshot.quantity.unit),"quantity.unit");require(tolerance(snapshot.quantity.tolerancePercent),"quantity.tolerance");require(text(snapshot.quantity.measurementBasis),"quantity.measurement_basis");if(profile.allowedUnits.length)require(profile.allowedUnits.includes(snapshot.quantity.unit),"quantity.profile_unit");
  require(positive(snapshot.price.unitPrice),"price.unit_price");require(/^[A-Z]{3}$/.test(snapshot.price.currency),"price.currency");require(text(snapshot.price.pricingBasis),"price.pricing_basis");require(positive(snapshot.price.estimatedTotal),"price.estimated_total");
  require(INCOTERMS_2020.includes(snapshot.delivery.incoterm),"delivery.incoterm");require(snapshot.delivery.incotermsVersion==="2020","delivery.incoterms_version");require(text(snapshot.delivery.namedPlace),"delivery.named_place");require(iso(snapshot.delivery.shipmentWindowStart),"delivery.shipment_window_start");require(iso(snapshot.delivery.shipmentWindowEnd),"delivery.shipment_window_end");if(iso(snapshot.delivery.shipmentWindowStart)&&iso(snapshot.delivery.shipmentWindowEnd))require(Date.parse(snapshot.delivery.shipmentWindowStart)<=Date.parse(snapshot.delivery.shipmentWindowEnd),"delivery.shipment_window_order");require(text(snapshot.delivery.laycanSemantics),"delivery.laycan_semantics");require(text(snapshot.delivery.packaging),"delivery.packaging");require(text(snapshot.delivery.shipmentMode),"delivery.shipment_mode");
  if(snapshot.inspection.required)for(const [key,value] of Object.entries(snapshot.inspection).filter(([key])=>key!=="required"))require(text(value),`inspection.${key}`);
  require(text(snapshot.payment.method),"payment.method");require(text(snapshot.payment.methodCode),"payment.method_code");require(text(snapshot.payment.timing),"payment.timing");require(text(snapshot.payment.dueTrigger),"payment.due_trigger");require(snapshot.payment.currency===snapshot.price.currency,"payment.currency_matches_price");if(["LETTER_OF_CREDIT","DOCUMENTARY_COLLECTION"].includes(snapshot.payment.methodCode))require(text(snapshot.payment.bankDocumentConditions),"payment.bank_document_conditions");
  const docs=new Set(snapshot.requiredDocuments.map(documentCode));for(const required of profile.requiredDocuments)require(docs.has(required),`documents.${required.toLowerCase()}`);
  for(const [key,value] of [["risk_transfer",snapshot.legal.riskTransfer],["title_transfer",snapshot.legal.titleTransfer],["governing_law",snapshot.legal.governingLaw],["force_majeure",snapshot.legal.forceMajeureTreatment],["hardship",snapshot.legal.hardshipTreatment],["claims",snapshot.legal.claimsTreatment],["default",snapshot.legal.defaultTreatment],["liability",snapshot.legal.liabilityTreatment],["trade_compliance",snapshot.legal.tradeComplianceTreatment]] as const)require(text(value),`legal.${key}`);
  require(snapshot.legal.cisgTreatment!=="LEGAL_REVIEW_REQUIRED"&&["APPLIES_WHERE_LEGALLY_APPLICABLE","EXPRESSLY_INCLUDED","EXPRESSLY_EXCLUDED"].includes(snapshot.legal.cisgTreatment),"legal.cisg_treatment");if(snapshot.legal.disputeResolution==="ICC_ARBITRATION"){require(snapshot.legal.arbitrationInstitution==="ICC","legal.arbitration_institution");require(text(snapshot.legal.arbitrationSeat),"legal.arbitration_seat");require(text(snapshot.legal.arbitrationLanguage),"legal.arbitration_language");require(snapshot.legal.arbitratorCount===1||snapshot.legal.arbitratorCount===3,"legal.arbitrator_count")}
  require(text(snapshot.platform.platformRole)&&/platform/i.test(snapshot.platform.platformRole)&&/only/i.test(snapshot.platform.platformRole),"platform.role");require(text(snapshot.platform.platformFeeTreatment),"platform.fee_treatment");
  const unique=[...new Set(missing)].sort();return Object.freeze({outcome:unique.length?"NOT_READY":"READY",missing:Object.freeze(unique),presentationPercent:applicable?Math.round(100*satisfied/applicable):0,applicableRequirementCount:applicable,satisfiedRequirementCount:satisfied,policyVersion:CONTRACT_READINESS_POLICY_VERSION});
}

export function fingerprintSnapshot(snapshot:ContractTermsSnapshot):string{return sha256({scope:"mvp-contract-snapshot/v1.1",snapshot})}
export function fingerprintApproval(input:Readonly<{snapshotFingerprint:string;party:ContractParty;organizationId:string;userId:string;approvedAt:string}>):string{return sha256({scope:"mvp-contract-terms-approval/v1.1",...input})}
export function fingerprintSignature(input:Readonly<{snapshotFingerprint:string;party:ContractParty;organizationId:string;signerUserId:string;authorityId:string;previewDocumentSha256:string;signedAt:string;correlationId:string}>):string{return sha256({scope:"mvp-contract-signature/v1.1",...input})}
export function fingerprintSigningAuthority(input:Readonly<{organizationId:string;userId:string;membershipId:string;grantedByUserId:string;grantedAt:string}>):string{return sha256({scope:"mvp-contract-signing-authority/v1",...input})}
export const VALID_TRANSITIONS:Readonly<Record<MvpContractState,readonly MvpContractState[]>>=Object.freeze({CONTRACT_PREPARATION:["CONTRACT_READY"],CONTRACT_READY:["AWAITING_SELLER_SIGNATURE","CONTRACT_PREPARATION"],AWAITING_SELLER_SIGNATURE:["AWAITING_BUYER_SIGNATURE","CONTRACT_PREPARATION"],AWAITING_BUYER_SIGNATURE:["EXECUTED","CONTRACT_PREPARATION"],EXECUTED:["EXECUTION_STARTED","DISPUTED","TERMINATED"],EXECUTION_STARTED:["DOCUMENTS_SUBMITTED","DISPUTED","TERMINATED"],DOCUMENTS_SUBMITTED:["DELIVERY_CONFIRMED","DISPUTED","TERMINATED"],DELIVERY_CONFIRMED:["SETTLEMENT_CONFIRMED","DISPUTED","TERMINATED"],SETTLEMENT_CONFIRMED:["TRADE_CLOSED","DISPUTED","TERMINATED"],TRADE_CLOSED:[],DISPUTED:[],TERMINATED:[]});
export function canTransition(from:MvpContractState,to:MvpContractState):boolean{return VALID_TRANSITIONS[from]?.includes(to)??false}
export interface LinkedAmendmentInstrument {readonly parentContractId:string;readonly parentSnapshotId:string;readonly instrumentReference:string;readonly status:"PROPOSED"|"EXECUTED";readonly notice:"SEPARATE_LINKED_INSTRUMENT_NOT_IN_PLACE_MUTATION"}
export function linkedAmendmentInstrument(parent:Pick<ContractTermsSnapshot,"contractId"|"snapshotId">,instrumentReference:string,status:"PROPOSED"|"EXECUTED"="PROPOSED"):LinkedAmendmentInstrument{return Object.freeze({parentContractId:parent.contractId,parentSnapshotId:parent.snapshotId,instrumentReference,status,notice:"SEPARATE_LINKED_INSTRUMENT_NOT_IN_PLACE_MUTATION"})}
