import assert from "node:assert/strict";
import test from "node:test";
import { generateContractPdf } from "./contractDocument.js";
import { canTransition, evaluateContractReadiness, fingerprintSnapshot, MVP_TEMPLATE_VERSION, UREA46_PROFILE_VERSION, type ContractTermsSnapshot } from "./domain.js";

const party=(id:string,name:string)=>({organizationId:id,profileRevisionId:`profile-${id}`,legalName:name,registrationJurisdiction:"SA",registrationIdentifiers:[{scheme:"commercial_registration",value:`CR-${id}`}],registeredAddress:{countryCode:"SA",addressLines:["King Fahd Road"]},authorizedRepresentative:`Representative ${name}`});
function snapshot(overrides:Record<string,unknown>={}):ContractTermsSnapshot{return {
  contractId:"contract-1",orderId:"order-1",tutelaReference:"TUTELA-contract-1",contractVersion:1,snapshotId:"11111111-1111-4111-8111-111111111111",snapshotCreatedAt:"2026-09-17T00:00:00.000Z",templateVersion:MVP_TEMPLATE_VERSION,commercialProfileVersion:UREA46_PROFILE_VERSION,
  seller:party("seller","Seller Legal Co"),buyer:party("buyer","Buyer Legal Co"),commodity:{name:"Urea 46%",grade:"Granular 46% N",productDescription:"Granular nitrogen fertilizer",origin:"Saudi Arabia",producer:"Named producer",specifications:[
    {code:"NITROGEN",label:"Nitrogen",value:"46.0",unit:"%",sourceReference:"offer-evidence-1"},{code:"BIURET",label:"Biuret",value:"agreed",unit:"%",sourceReference:"offer-evidence-1"},{code:"MOISTURE",label:"Moisture",value:"agreed",unit:"%",sourceReference:"offer-evidence-1"},{code:"PARTICLE_SIZE",label:"Particle size distribution",value:"agreed",sourceReference:"offer-evidence-1"},{code:"APPEARANCE",label:"Appearance",value:"white granular",sourceReference:"offer-evidence-1"}]},
  quantity:{amount:"1000",unit:"MT",tolerancePercent:"5"},price:{unitPrice:"300",currency:"USD",pricingBasis:"Fixed price",estimatedTotal:"300000"},delivery:{incoterm:"CFR",incotermsVersion:"2020",namedPlace:"Jebel Ali Port, UAE",shipmentWindowStart:"2026-10-01T00:00:00.000Z",shipmentWindowEnd:"2026-10-31T00:00:00.000Z",packaging:"50 kg bags",partialShipmentPolicy:"NOT_ALLOWED"},inspection:{required:true,bodyOrMethod:"SGS or mutually agreed equivalent",inspectionPoint:"Load port",quantityDetermination:"Draft survey",qualityDetermination:"Certificate of analysis",finalityAndClaims:"Final at load port subject to documented fraud or manifest error"},payment:{method:"Irrevocable documentary letter of credit",timing:"At sight against compliant documents",currency:"USD",bankDocumentConditions:"UCP reference requires separate counsel confirmation"},requiredDocuments:["Commercial Invoice","Bill of Lading","Certificate of Origin","Quality Certificate","Quantity Certificate","Packing List"],legal:{riskTransfer:"At loading on board under CFR Incoterms 2020",titleTransfer:"Upon seller receipt of cleared funds",governingLaw:"Laws of the Kingdom of Saudi Arabia",cisgTreatment:"LEGAL_REVIEW_REQUIRED",disputeResolution:"ICC_ARBITRATION",arbitrationInstitution:"ICC",arbitrationSeat:"Riyadh, Saudi Arabia",arbitrationLanguage:"English",arbitratorCount:1,forceMajeureTreatment:"Original TUTELA clause aligned conceptually with ICC Force Majeure Clause 2020; notice and mitigation required",hardshipTreatment:"Good-faith renegotiation followed by termination if unresolved"},platform:{platformFeeTreatment:"Fees are separately invoiced and do not alter sale price",snapshotVersion:1,sourceOrderFingerprint:"sha256:"+"a".repeat(64),sourceTermsFingerprint:"sha256:"+"b".repeat(64)},specialConditions:[],...overrides,
} as ContractTermsSnapshot}

test("complete Urea 46 profile is READY and fingerprint deterministic",()=>{const value=snapshot();assert.deepEqual(evaluateContractReadiness(value),{outcome:"READY",missing:[],presentationPercent:100,policyVersion:"mvp-contract-readiness/v1"});assert.equal(fingerprintSnapshot(value),fingerprintSnapshot(structuredClone(value)))});
test("CFR without named destination and price without matching currency fail closed",()=>{const value=snapshot({delivery:{...snapshot().delivery,namedPlace:""},payment:{...snapshot().payment,currency:"EUR"}});const result=evaluateContractReadiness(value);assert.equal(result.outcome,"NOT_READY");assert.ok(result.missing.includes("delivery.named_place"));assert.ok(result.missing.includes("payment.currency_matches_price"))});
test("Urea profile never invents mandatory specification values",()=>{const value=snapshot({commodity:{...snapshot().commodity,specifications:snapshot().commodity.specifications.filter(v=>v.code!=="BIURET")}});const result=evaluateContractReadiness(value);assert.equal(result.outcome,"NOT_READY");assert.ok(result.missing.includes("urea46.specification.biuret"))});
test("lifecycle rejects edits after execution and closes only from settlement",()=>{assert.equal(canTransition("AWAITING_BUYER_SIGNATURE","EXECUTED"),true);assert.equal(canTransition("EXECUTED","CONTRACT_PREPARATION"),false);assert.equal(canTransition("DELIVERY_CONFIRMED","TRADE_CLOSED"),false);assert.equal(canTransition("SETTLEMENT_CONFIRMED","TRADE_CLOSED"),true);assert.equal(canTransition("TRADE_CLOSED","DISPUTED"),false)});
test("deterministic PDF binds exact snapshot and signature evidence",()=>{const value=snapshot();const previewA=generateContractPdf(value),previewB=generateContractPdf(value);assert.deepEqual(previewA.bytes,previewB.bytes);assert.equal(previewA.sha256,previewB.sha256);assert.ok(previewA.bytes.subarray(0,8).toString().startsWith("%PDF-1."));assert.ok(previewA.pageCount>=3);const executed=generateContractPdf(value,[{party:"SELLER",signerName:"Seller Signer",organizationName:"Seller Legal Co",signedAt:"2026-09-18T00:00:00.000Z",signatureFingerprint:"sha256:"+"c".repeat(64)},{party:"BUYER",signerName:"Buyer Signer",organizationName:"Buyer Legal Co",signedAt:"2026-09-18T01:00:00.000Z",signatureFingerprint:"sha256:"+"d".repeat(64)}],true);assert.notEqual(executed.sha256,previewA.sha256);assert.ok(executed.bytes.includes(Buffer.from("EXECUTED CONTRACT ARTIFACT")))});
